language: c
sudo: required
services:
  - docker

env:
  global:
    # TODO convert to DOCKER_HUB_USERNAME and DOCKER_HUB_PASSWORD for
    # Numenta's docker hub account
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
    - secure: ""
    - secure: ""

script:
  # We're only interested in x86_64.
  - docker build --rm -t quay.io/numenta/manylinux1_x86_64_centos6:$COMMIT -f docker/Dockerfile-x86_64 docker/


deploy:
  provider: script
  # TODO Update docker/deploy.sh to work with numenta's environment. Better
  # yet, make it an autobuild in docker hub repo
  # numenta/manylinux1_x86_64_centos6.
  script: docker/deploy.sh
  on:
    branch: master
